# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#These are hide by us
#title: How to use abortion pill
#email: your-email@example.com
#description: HowToUse is a community that believes all women deserve access to a safe abortion option. Your body. Your choice. Your right to know.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
#upto here
title: How to Use the Abortion Pills | Step By Step Instructions
description: HowToUse is a community that believes all women deserve access to a safe abortion option. Your body. Your choice. Your right to know.
tagline: Site Tagline
author:
  name: How to use abortion pill staff
  email: info@howtouseabortionpill.org
  twitter:
    username : "@HTUabortionpill"
  feedburner: feedname
facebook:
 num_posts: 5
 width: 580
 colorscheme: light
logo: https://www.howtouseabortionpill.org/sw/assets/images/LOGO.svg
social:
  name: How to use abortion pill
  links:
    - https://twitter.com/HTUabortionpill/
    - https://www.facebook.com/HTUabortionpill/
    - https://pinterest.com/howtouseabortionpill/

webserver_headers:
  "Access-Control-Allow-Origin": "*"
  "Server": "www.howtouseabortionpill.org"

url: https://www.howtouseabortionpill.org
#url : https://beta.howtouseabortionpill.herokuapp.com
#url: http://figsfromspace.gitlab.io
baseurl: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

collections:
  staff:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

languages: ["es"]

exclude_from_localizations: ["javascript", "images", "css"]

default_locale_in_subfolder: false

include: [_redirects]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass: 
  sass_dir: _sass/
  style: compressed